slogo_team14: backend.Line Class Reference
backend.Line Class Reference
Public Member Functions
Line (Point start, Point end, Color color, int width)
Color getColor ()
int getWidth ()
Point getStartPoint ()
Point getEndPoint ()
String toString ()
Protected Member Functions
boolean intersects (Line otherLine)
boolean isVisible ()
double getLength ()
Private Member Functions
Point convertDoublePoint (Point2D ptd)
Private Attributes
Color color
int width
Static Private Attributes
static final long serialVersionUID = 1
Detailed Description
Definition at line 7 of file Line.java.
Constructor & Destructor Documentation
backend.Line.Line (Point start, Point end, Color color, int width)
Definition at line 13 of file Line.java.
References backend.Line.color, and backend.Line.width.
Member Function Documentation
Point backend.Line.convertDoublePoint (Point2D ptd) private
Definition at line 43 of file Line.java.
Referenced by backend.Line.getEndPoint(), and backend.Line.getStartPoint().
Color backend.Line.getColor ()
Definition at line 27 of file Line.java.
References backend.Line.color.
Point backend.Line.getEndPoint ()
Definition at line 39 of file Line.java.
References backend.Line.convertDoublePoint().
Referenced by backend.Line.toString().
double backend.Line.getLength () protected
Definition at line 47 of file Line.java.
Point backend.Line.getStartPoint ()
Definition at line 35 of file Line.java.
References backend.Line.convertDoublePoint().
Referenced by backend.Line.toString().
int backend.Line.getWidth ()
Definition at line 31 of file Line.java.
References backend.Line.width.
boolean backend.Line.intersects (Line otherLine) protected
Definition at line 19 of file Line.java.
boolean backend.Line.isVisible () protected
Definition at line 23 of file Line.java.
String backend.Line.toString ()
Definition at line 53 of file Line.java.
References backend.Line.getEndPoint(), and backend.Line.getStartPoint().
Member Data Documentation
Color backend.Line.color private
Definition at line 10 of file Line.java.
Referenced by backend.Line.getColor(), and backend.Line.Line().
final long backend.Line.serialVersionUID = 1 static private
Definition at line 9 of file Line.java.
int backend.Line.width private
Definition at line 11 of file Line.java.
Referenced by backend.Line.getWidth(), and backend.Line.Line().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/Line.java