slogo_team14: gui.textAreas.CommandBox Class Reference
gui.textAreas.CommandBox Class Reference
Public Member Functions
CommandBox (double prefHeightRatio, double prefWidthRatio, double xLocation, double yLocation, double overlayWidth, double overlayHeight, String initText, boolean isPrompt, RunButtons runButtons)
String getText ()
void updateText ()
Public Member Functions inherited from gui.textAreas.AbstractEditableTextBox
AbstractEditableTextBox (double prefHeightRatio, double prefWidthRatio, double xLocation, double yLocation, double overlayWidth, double overlayHeight, String initText, boolean isPrompt)
void setText (String s)
TextArea makeTextArea ()
void setRegionPreferences ()
void addTextAreaToRegion ()
abstract void updateText ()
double getxLocation ()
void setxLocation (double xLocation)
double getyLocation ()
void setyLocation (double yLocation)
Private Member Functions
void setCommandBoxPromptText (String promptText)
Private Attributes
RunButtons runButtons
Static Private Attributes
static double BOX_RATIO = 0.8
static double SPACING_AMT = 10
Additional Inherited Members
Public Attributes inherited from gui.textAreas.AbstractEditableTextBox
boolean isPrompt
Protected Attributes inherited from gui.textAreas.AbstractEditableTextBox
double prefHeightRatio
double prefWidthRatio
double overlayWidth
double overlayHeight
String initText
TextArea textArea
Label label
double titleHeightPct = .1
Detailed Description
Definition at line 7 of file CommandBox.java.
Constructor & Destructor Documentation
gui.textAreas.CommandBox.CommandBox (double prefHeightRatio, double prefWidthRatio, double xLocation, double yLocation, double overlayWidth, double overlayHeight, String initText, boolean isPrompt, RunButtons runButtons)
Definition at line 13 of file CommandBox.java.
References gui.textAreas.AbstractEditableTextBox.label, gui.textAreas.CommandBox.runButtons, gui.textAreas.CommandBox.setCommandBoxPromptText(), gui.textAreas.AbstractEditableTextBox.textArea, and gui.textAreas.AbstractEditableTextBox.titleHeightPct.
Member Function Documentation
String gui.textAreas.CommandBox.getText ()
Definition at line 41 of file CommandBox.java.
References gui.textAreas.AbstractEditableTextBox.textArea.
Referenced by gui.SlogoTab.setButtonActions().
void gui.textAreas.CommandBox.setCommandBoxPromptText (String promptText) private
Definition at line 45 of file CommandBox.java.
References gui.textAreas.AbstractEditableTextBox.textArea.
Referenced by gui.textAreas.CommandBox.CommandBox().
void gui.textAreas.CommandBox.updateText ()
Definition at line 51 of file CommandBox.java.
Member Data Documentation
double gui.textAreas.CommandBox.BOX_RATIO = 0.8 static private
Definition at line 9 of file CommandBox.java.
RunButtons gui.textAreas.CommandBox.runButtons private
Definition at line 11 of file CommandBox.java.
Referenced by gui.textAreas.CommandBox.CommandBox().
double gui.textAreas.CommandBox.SPACING_AMT = 10 static private
Definition at line 10 of file CommandBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/gui/textAreas/CommandBox.java