slogo_team14: backend.Pen Class Reference
backend.Pen Class Reference
Public Member Functions
Pen (Color color, int width, boolean isDown)
Color getColor ()
int getWidth ()
List< Line > getLines ()
boolean clearLines ()
boolean isDown ()
void setColor (Color color)
void setWidth (int width)
void setDown (boolean isDown)
Line drawLine (Point start, Point end)
Private Attributes
Color color
int width
boolean isDown
ArrayList< Line > lines
Detailed Description
Definition at line 8 of file Pen.java.
Constructor & Destructor Documentation
backend.Pen.Pen (Color color, int width, boolean isDown)
Definition at line 15 of file Pen.java.
References backend.Pen.color, backend.Pen.isDown(), and backend.Pen.width.
Member Function Documentation
boolean backend.Pen.clearLines ()
Definition at line 34 of file Pen.java.
Referenced by backend.Turtle.clearLines().
Line backend.Pen.drawLine (Point start, Point end)
Definition at line 59 of file Pen.java.
References backend.Pen.isDown().
Referenced by backend.Turtle.moveToPoint().
Color backend.Pen.getColor ()
Definition at line 22 of file Pen.java.
References backend.Pen.color.
Referenced by backend.command.GetPenColor.execute().
List<Line> backend.Pen.getLines ()
Definition at line 30 of file Pen.java.
References backend.Pen.lines.
Referenced by backend.Turtle.getLines().
int backend.Pen.getWidth ()
Definition at line 26 of file Pen.java.
References backend.Pen.width.
boolean backend.Pen.isDown ()
Definition at line 43 of file Pen.java.
Referenced by backend.Pen.drawLine(), backend.Pen.Pen(), and backend.Pen.setDown().
void backend.Pen.setColor (Color color)
Definition at line 47 of file Pen.java.
References backend.Pen.color.
Referenced by backend.command.SetPenColor.execute().
void backend.Pen.setDown (boolean isDown)
Definition at line 55 of file Pen.java.
References backend.Pen.isDown().
Referenced by backend.Turtle.setPenDown(), and backend.Turtle.setPenUp().
void backend.Pen.setWidth (int width)
Definition at line 51 of file Pen.java.
References backend.Pen.width.
Referenced by backend.command.SetPenSize.execute().
Member Data Documentation
Color backend.Pen.color private
Definition at line 10 of file Pen.java.
Referenced by backend.Pen.getColor(), backend.Pen.Pen(), and backend.Pen.setColor().
boolean backend.Pen.isDown private
Definition at line 12 of file Pen.java.
Referenced by backend.Turtle.isPenDown().
ArrayList<Line> backend.Pen.lines private
Definition at line 13 of file Pen.java.
Referenced by backend.Pen.getLines().
int backend.Pen.width private
Definition at line 11 of file Pen.java.
Referenced by backend.Pen.getWidth(), backend.Pen.Pen(), and backend.Pen.setWidth().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/Pen.java