slogo_team14: gui.textAreas.UserVariablesBox Class Reference
gui.textAreas.UserVariablesBox Class Reference
Public Member Functions
UserVariablesBox (double prefHeightRatio, double prefWidthRatio, double xLocation, double yLocation, double overlayWidth, double overlayHeight, String initText, boolean isPrompt)
VBox getFields ()
VBox getLabels ()
void updateText ()
Public Member Functions inherited from gui.textAreas.AbstractEditableTextBox
AbstractEditableTextBox (double prefHeightRatio, double prefWidthRatio, double xLocation, double yLocation, double overlayWidth, double overlayHeight, String initText, boolean isPrompt)
void setText (String s)
TextArea makeTextArea ()
void setRegionPreferences ()
void addTextAreaToRegion ()
abstract void updateText ()
double getxLocation ()
void setxLocation (double xLocation)
double getyLocation ()
void setyLocation (double yLocation)
Private Attributes
VBox myLabels
VBox myFields
HBox myData
Static Private Attributes
static double SIDE_OFFSET = 5.0
Additional Inherited Members
Public Attributes inherited from gui.textAreas.AbstractEditableTextBox
boolean isPrompt
Protected Attributes inherited from gui.textAreas.AbstractEditableTextBox
double prefHeightRatio
double prefWidthRatio
double overlayWidth
double overlayHeight
String initText
TextArea textArea
Label label
double titleHeightPct = .1
Detailed Description
Definition at line 7 of file UserVariablesBox.java.
Constructor & Destructor Documentation
gui.textAreas.UserVariablesBox.UserVariablesBox (double prefHeightRatio, double prefWidthRatio, double xLocation, double yLocation, double overlayWidth, double overlayHeight, String initText, boolean isPrompt)
Definition at line 13 of file UserVariablesBox.java.
References gui.textAreas.AbstractEditableTextBox.addTextAreaToRegion(), gui.textAreas.AbstractEditableTextBox.initText, gui.textAreas.AbstractEditableTextBox.isPrompt, gui.textAreas.AbstractEditableTextBox.label, gui.textAreas.AbstractEditableTextBox.makeTextArea(), gui.textAreas.AbstractEditableTextBox.overlayHeight, gui.textAreas.AbstractEditableTextBox.overlayWidth, gui.textAreas.AbstractEditableTextBox.prefHeightRatio, gui.textAreas.AbstractEditableTextBox.prefWidthRatio, gui.textAreas.AbstractEditableTextBox.setRegionPreferences(), gui.textAreas.AbstractEditableTextBox.setxLocation(), gui.textAreas.AbstractEditableTextBox.setyLocation(), gui.textAreas.AbstractEditableTextBox.textArea, and gui.textAreas.AbstractEditableTextBox.titleHeightPct.
Member Function Documentation
VBox gui.textAreas.UserVariablesBox.getFields ()
Definition at line 55 of file UserVariablesBox.java.
References gui.textAreas.UserVariablesBox.myFields.
Referenced by gui.SlogoTab.setVariablesBox().
VBox gui.textAreas.UserVariablesBox.getLabels ()
Definition at line 59 of file UserVariablesBox.java.
References gui.textAreas.UserVariablesBox.myLabels.
Referenced by gui.SlogoTab.setVariablesBox().
void gui.textAreas.UserVariablesBox.updateText ()
Definition at line 64 of file UserVariablesBox.java.
Member Data Documentation
HBox gui.textAreas.UserVariablesBox.myData private
Definition at line 11 of file UserVariablesBox.java.
VBox gui.textAreas.UserVariablesBox.myFields private
Definition at line 10 of file UserVariablesBox.java.
Referenced by gui.textAreas.UserVariablesBox.getFields().
VBox gui.textAreas.UserVariablesBox.myLabels private
Definition at line 9 of file UserVariablesBox.java.
Referenced by gui.textAreas.UserVariablesBox.getLabels().
double gui.textAreas.UserVariablesBox.SIDE_OFFSET = 5.0 static private
Definition at line 8 of file UserVariablesBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/gui/textAreas/UserVariablesBox.java