slogo_team14: gui.TurtleImage Class Reference
gui.TurtleImage Class Reference
Public Member Functions
TurtleImage (Turtle turtle)
void setDefaultImagePath ()
void updateImage ()
void sizeTurtle (double screenWidth, double screenHeight)
void orientTurtle (Turtle turtle)
void setLocation (Point p)
Protected Attributes
double turtleWidthPct = .05
String defaultImagePath = "../resources/sea_turtle.png"
Turtle turtle
Detailed Description
Definition at line 11 of file TurtleImage.java.
Constructor & Destructor Documentation
gui.TurtleImage.TurtleImage (Turtle turtle)
Definition at line 16 of file TurtleImage.java.
References gui.TurtleImage.turtle, and gui.TurtleImage.updateImage().
Member Function Documentation
void gui.TurtleImage.orientTurtle (Turtle turtle)
Definition at line 53 of file TurtleImage.java.
References backend.Heading.getAngle(), and backend.Turtle.getHeading().
Referenced by gui.DrawingArea.drawTurtles().
void gui.TurtleImage.setDefaultImagePath ()
Definition at line 25 of file TurtleImage.java.
References backend.Turtle.getImagePath(), and backend.Turtle.setImageByFullPath().
void gui.TurtleImage.setLocation (Point p)
Definition at line 59 of file TurtleImage.java.
Referenced by gui.DrawingArea.drawTurtles().
void gui.TurtleImage.sizeTurtle (double screenWidth, double screenHeight)
Definition at line 44 of file TurtleImage.java.
Referenced by gui.DrawingArea.drawTurtles().
void gui.TurtleImage.updateImage ()
Definition at line 33 of file TurtleImage.java.
References backend.Turtle.getImagePath().
Referenced by gui.DrawingArea.drawTurtles(), and gui.TurtleImage.TurtleImage().
Member Data Documentation
String gui.TurtleImage.defaultImagePath = "../resources/sea_turtle.png" protected
Definition at line 14 of file TurtleImage.java.
Turtle gui.TurtleImage.turtle protected
Definition at line 15 of file TurtleImage.java.
Referenced by gui.TurtleImage.TurtleImage().
double gui.TurtleImage.turtleWidthPct = .05 protected
Definition at line 13 of file TurtleImage.java.
Referenced by gui.DrawingArea.positionPointRelativeToLines().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/gui/TurtleImage.java