slogo_team14: backend.command.SetPenSize Class Reference
backend.command.SetPenSize Class Reference
Public Member Functions
SetPenSize (StringPair stringPair, Command parent, Model model)
Double execute (Turtle t)
Public Member Functions inherited from backend.command.PixelsTurtleCommand
PixelsTurtleCommand (StringPair stringPair, Command parent, Model model)
Public Member Functions inherited from backend.command.ActiveTurtleCommand
ActiveTurtleCommand (StringPair stringPair, int numParams, Command parent, Model model)
Double execute ()
Public Member Functions inherited from backend.command.TurtleCommand
TurtleCommand (StringPair stringPair, int numParams, Command parent, Model model)
Public Member Functions inherited from backend.command.ModelCommand
ModelCommand (StringPair stringPair, int numParams, Command parent, Model model)
Public Member Functions inherited from backend.command.Command
Command (StringPair stringPair, int numParams, Command parent)
abstract Double execute ()
String toString ()
String getTypedString ()
String getProperty ()
boolean needsParams ()
void setParam (Command newParam)
Command getParam (int index)
boolean hasParent ()
Double executeParam (int paramIndex)
Double getReturnVal ()
Double getParamReturnVal (int paramIndex)
ArrayList< Command > getParams ()
Command getParent ()
int getIndentLevel ()
Additional Inherited Members
Protected Member Functions inherited from backend.command.PixelsTurtleCommand
Double pixels ()
Protected Member Functions inherited from backend.command.ActiveTurtleCommand
abstract Double execute (Turtle turtle)
Protected Member Functions inherited from backend.command.TurtleCommand
List< Turtle > allTurtles ()
List< Turtle > activeTurtles ()
Protected Member Functions inherited from backend.command.ModelCommand
Map< String, Variable > userVariables ()
Map< String, UserInstructionContainer > userInstructions ()
Grid grid ()
BiMap< Integer, Color > colorMap ()
BiMap< Integer, String > imageMap ()
Color paramToColor (int paramIndex)
String paramToImage (int paramIndex)
Protected Member Functions inherited from backend.command.Command
String preParamsFormatString ()
String indentString ()
String postParamsFormatString ()
String interParamFormatString ()
boolean parentIsList ()
Protected Attributes inherited from backend.command.Command
int numParams
ArrayList< Command > params
Command parent
Package Functions inherited from backend.command.Command
public< T extends Command > T getParam (int index, Class< T > type)
Package Attributes inherited from backend.command.Command
int indentLevel
Double returnVal
Detailed Description
Definition at line 5 of file SetPenSize.java.
Constructor & Destructor Documentation
backend.command.SetPenSize.SetPenSize (StringPair stringPair, Command parent, Model model)
Definition at line 7 of file SetPenSize.java.
Member Function Documentation
Double backend.command.SetPenSize.execute (Turtle t)
Definition at line 11 of file SetPenSize.java.
References backend.Turtle.getPen(), backend.command.PixelsTurtleCommand.pixels(), and backend.Pen.setWidth().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/command/SetPenSize.java