slogo_team14: gui.Main Class Reference
gui.Main Class Reference
Public Member Functions
Main ()
void start (Stage primaryStage) throws Exception
SlogoTab getActiveTab ()
void setActiveTab (SlogoTab activeTab)
Static Public Member Functions
static void main (String[] args)
Package Attributes
Model myModel = new Model()
Stage stage
Scene scene
Private Member Functions
void setStageToFillWindow (Double screenWidth, Double screenHeight)
double getScreenHeight (Rectangle2D bounds)
double getScreenWidth (Rectangle2D bounds)
Private Attributes
double topMenuHeightPct = .025
double tabPanelHeightPct = .03
SlogoTab activeTab
HashMap< SlogoTab, Model > tabMap = new HashMap<>()
HashMap< Tab, SlogoTab > tabSLogoTabMap = new HashMap<>()
Group root = new Group()
Detailed Description
Definition at line 32 of file Main.java.
Constructor & Destructor Documentation
gui.Main.Main ()
Definition at line 47 of file Main.java.
Member Function Documentation
SlogoTab gui.Main.getActiveTab ()
Definition at line 113 of file Main.java.
References gui.Main.activeTab.
double gui.Main.getScreenHeight (Rectangle2D bounds) private
Definition at line 95 of file Main.java.
Referenced by gui.Main.start().
double gui.Main.getScreenWidth (Rectangle2D bounds) private
Definition at line 102 of file Main.java.
Referenced by gui.Main.start().
static void gui.Main.main (String[] args) static
Definition at line 109 of file Main.java.
void gui.Main.setActiveTab (SlogoTab activeTab)
Definition at line 117 of file Main.java.
References gui.Main.activeTab.
Referenced by gui.TabPanel.makeNewTab(), and gui.TabPanel.makeTabPane().
void gui.Main.setStageToFillWindow (Double screenWidth, Double screenHeight) private
Definition at line 85 of file Main.java.
Referenced by gui.Main.start().
void gui.Main.start (Stage primaryStage) throws Exception
Definition at line 53 of file Main.java.
References gui.Main.getScreenHeight(), gui.Main.getScreenWidth(), gui.TabPanel.makeNewTab(), gui.Main.setStageToFillWindow(), and gui.TopMenu.tabPanel.
Member Data Documentation
SlogoTab gui.Main.activeTab private
Definition at line 36 of file Main.java.
Referenced by gui.Main.getActiveTab(), and gui.Main.setActiveTab().
Model gui.Main.myModel = new Model() package
Definition at line 42 of file Main.java.
Group gui.Main.root = new Group() private
Definition at line 39 of file Main.java.
Scene gui.Main.scene package
Definition at line 46 of file Main.java.
Stage gui.Main.stage package
Definition at line 45 of file Main.java.
HashMap<SlogoTab, Model> gui.Main.tabMap = new HashMap<>() private
Definition at line 37 of file Main.java.
double gui.Main.tabPanelHeightPct = .03 private
Definition at line 35 of file Main.java.
HashMap<Tab, SlogoTab> gui.Main.tabSLogoTabMap = new HashMap<>() private
Definition at line 38 of file Main.java.
double gui.Main.topMenuHeightPct = .025 private
Definition at line 34 of file Main.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/gui/Main.java