slogo_team14: gui.textAreas.AbstractEditableTextBox Class Reference
gui.textAreas.AbstractEditableTextBox Class Reference abstract
Public Member Functions
AbstractEditableTextBox (double prefHeightRatio, double prefWidthRatio, double xLocation, double yLocation, double overlayWidth, double overlayHeight, String initText, boolean isPrompt)
void setText (String s)
TextArea makeTextArea ()
void setRegionPreferences ()
void addTextAreaToRegion ()
abstract void updateText ()
double getxLocation ()
void setxLocation (double xLocation)
double getyLocation ()
void setyLocation (double yLocation)
Public Attributes
boolean isPrompt
Protected Attributes
double prefHeightRatio
double prefWidthRatio
double overlayWidth
double overlayHeight
String initText
TextArea textArea
Label label
double titleHeightPct = .1
Private Member Functions
void makeTitle ()
Private Attributes
double xLocation
double yLocation
Detailed Description
Definition at line 18 of file AbstractEditableTextBox.java.
Constructor & Destructor Documentation
gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox (double prefHeightRatio, double prefWidthRatio, double xLocation, double yLocation, double overlayWidth, double overlayHeight, String initText, boolean isPrompt)
Definition at line 34 of file AbstractEditableTextBox.java.
References gui.textAreas.AbstractEditableTextBox.initText, gui.textAreas.AbstractEditableTextBox.isPrompt, gui.textAreas.AbstractEditableTextBox.makeTextArea(), gui.textAreas.AbstractEditableTextBox.makeTitle(), gui.textAreas.AbstractEditableTextBox.overlayHeight, gui.textAreas.AbstractEditableTextBox.overlayWidth, gui.textAreas.AbstractEditableTextBox.prefHeightRatio, gui.textAreas.AbstractEditableTextBox.prefWidthRatio, gui.textAreas.AbstractEditableTextBox.setRegionPreferences(), gui.textAreas.AbstractEditableTextBox.setxLocation(), and gui.textAreas.AbstractEditableTextBox.setyLocation().
Member Function Documentation
void gui.textAreas.AbstractEditableTextBox.addTextAreaToRegion ()
Definition at line 105 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
double gui.textAreas.AbstractEditableTextBox.getxLocation ()
Definition at line 113 of file AbstractEditableTextBox.java.
References gui.textAreas.AbstractEditableTextBox.xLocation.
Referenced by gui.SlogoTab.SlogoTab().
double gui.textAreas.AbstractEditableTextBox.getyLocation ()
Definition at line 121 of file AbstractEditableTextBox.java.
References gui.textAreas.AbstractEditableTextBox.yLocation.
Referenced by gui.SlogoTab.SlogoTab().
TextArea gui.textAreas.AbstractEditableTextBox.makeTextArea ()
Definition at line 63 of file AbstractEditableTextBox.java.
References gui.textAreas.AbstractEditableTextBox.textArea.
Referenced by gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
void gui.textAreas.AbstractEditableTextBox.makeTitle () private
Definition at line 83 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox().
void gui.textAreas.AbstractEditableTextBox.setRegionPreferences ()
Definition at line 98 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
void gui.textAreas.AbstractEditableTextBox.setText (String s)
Definition at line 58 of file AbstractEditableTextBox.java.
Referenced by gui.SlogoTab.updatePanels().
void gui.textAreas.AbstractEditableTextBox.setxLocation (double xLocation)
Definition at line 117 of file AbstractEditableTextBox.java.
References gui.textAreas.AbstractEditableTextBox.xLocation.
Referenced by gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
void gui.textAreas.AbstractEditableTextBox.setyLocation (double yLocation)
Definition at line 125 of file AbstractEditableTextBox.java.
References gui.textAreas.AbstractEditableTextBox.yLocation.
Referenced by gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
abstract void gui.textAreas.AbstractEditableTextBox.updateText () abstract
Member Data Documentation
String gui.textAreas.AbstractEditableTextBox.initText protected
Definition at line 26 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
boolean gui.textAreas.AbstractEditableTextBox.isPrompt
Definition at line 29 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
Label gui.textAreas.AbstractEditableTextBox.label protected
Definition at line 28 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.CommandBox.CommandBox(), gui.textAreas.PreviousCommandsBox.PreviousCommandsBox(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
double gui.textAreas.AbstractEditableTextBox.overlayHeight protected
Definition at line 25 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
double gui.textAreas.AbstractEditableTextBox.overlayWidth protected
Definition at line 24 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
double gui.textAreas.AbstractEditableTextBox.prefHeightRatio protected
Definition at line 20 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
double gui.textAreas.AbstractEditableTextBox.prefWidthRatio protected
Definition at line 21 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.AbstractEditableTextBox.AbstractEditableTextBox(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
TextArea gui.textAreas.AbstractEditableTextBox.textArea protected
Definition at line 27 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.CommandBox.CommandBox(), gui.textAreas.CommandBox.getText(), gui.textAreas.AbstractEditableTextBox.makeTextArea(), gui.textAreas.PreviousCommandsBox.PreviousCommandsBox(), gui.textAreas.CommandBox.setCommandBoxPromptText(), gui.textAreas.StatusBox.StatusBox(), gui.textAreas.UserFunctionsAndCommands.UserFunctionsAndCommands(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
double gui.textAreas.AbstractEditableTextBox.titleHeightPct = .1 protected
Definition at line 32 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.CommandBox.CommandBox(), gui.textAreas.PreviousCommandsBox.PreviousCommandsBox(), and gui.textAreas.UserVariablesBox.UserVariablesBox().
double gui.textAreas.AbstractEditableTextBox.xLocation private
Definition at line 22 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.AbstractEditableTextBox.getxLocation(), and gui.textAreas.AbstractEditableTextBox.setxLocation().
double gui.textAreas.AbstractEditableTextBox.yLocation private
Definition at line 23 of file AbstractEditableTextBox.java.
Referenced by gui.textAreas.AbstractEditableTextBox.getyLocation(), and gui.textAreas.AbstractEditableTextBox.setyLocation().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/gui/textAreas/AbstractEditableTextBox.java