slogo_team14: backend.Heading Class Reference
backend.Heading Class Reference
Public Member Functions
Heading (double angle)
void setAngle (double newAngle)
double getAngle ()
double getAngleRads ()
Private Attributes
double angle
Detailed Description
Definition at line 5 of file Heading.java.
Constructor & Destructor Documentation
backend.Heading.Heading (double angle)
Definition at line 9 of file Heading.java.
References backend.Heading.angle.
Member Function Documentation
double backend.Heading.getAngle ()
Definition at line 17 of file Heading.java.
References backend.Heading.angle.
Referenced by backend.command.Heading.execute(), gui.TurtleImage.orientTurtle(), backend.Turtle.rotateLeft(), backend.Turtle.rotateRight(), and backend.Turtle.setHeading().
double backend.Heading.getAngleRads ()
Definition at line 21 of file Heading.java.
Referenced by backend.Turtle.move().
void backend.Heading.setAngle (double newAngle)
Definition at line 13 of file Heading.java.
Member Data Documentation
double backend.Heading.angle private
Definition at line 7 of file Heading.java.
Referenced by backend.Heading.getAngle(), and backend.Heading.Heading().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/Heading.java