slogo_team14: backend.StringPair Class Reference
backend.StringPair Class Reference
Public Member Functions
StringPair (String prop, String val)
String getProperty ()
String getValue ()
Private Attributes
String property
String value
Detailed Description
Definition at line 3 of file StringPair.java.
Constructor & Destructor Documentation
backend.StringPair.StringPair (String prop, String val)
Definition at line 7 of file StringPair.java.
Member Function Documentation
String backend.StringPair.getProperty ()
Definition at line 12 of file StringPair.java.
References backend.StringPair.property.
Referenced by backend.command.CommandFactory.getCommand(), and backend.command.Command.getProperty().
String backend.StringPair.getValue ()
Definition at line 16 of file StringPair.java.
References backend.StringPair.value.
Referenced by backend.command.Constant.Constant(), and backend.command.Command.getTypedString().
Member Data Documentation
String backend.StringPair.property private
Definition at line 4 of file StringPair.java.
Referenced by backend.StringPair.getProperty().
String backend.StringPair.value private
Definition at line 5 of file StringPair.java.
Referenced by backend.StringPair.getValue().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/StringPair.java