slogo_team14: backend.UserInstructionContainer Class Reference
backend.UserInstructionContainer Class Reference
Public Member Functions
UserInstructionContainer (CommandList vars, CommandList coms)
CommandList getVarNames ()
CommandList getCommands ()
Private Attributes
CommandList varNames
CommandList commands
Detailed Description
Definition at line 5 of file UserInstructionContainer.java.
Constructor & Destructor Documentation
backend.UserInstructionContainer.UserInstructionContainer (CommandList vars, CommandList coms)
Definition at line 11 of file UserInstructionContainer.java.
Member Function Documentation
CommandList backend.UserInstructionContainer.getCommands ()
Definition at line 20 of file UserInstructionContainer.java.
References backend.UserInstructionContainer.commands.
Referenced by backend.command.UserInstructionRetriever.execute().
CommandList backend.UserInstructionContainer.getVarNames ()
Definition at line 16 of file UserInstructionContainer.java.
References backend.UserInstructionContainer.varNames.
Referenced by backend.command.UserInstructionRetriever.execute(), and backend.command.UserInstructionRetriever.getNumParams().
Member Data Documentation
CommandList backend.UserInstructionContainer.commands private
Definition at line 8 of file UserInstructionContainer.java.
Referenced by backend.UserInstructionContainer.getCommands().
CommandList backend.UserInstructionContainer.varNames private
Definition at line 7 of file UserInstructionContainer.java.
Referenced by backend.UserInstructionContainer.getVarNames().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/UserInstructionContainer.java