slogo_team14: backend.Grid Class Reference
backend.Grid Class Reference
Public Member Functions
Grid (Dimension size, BiIndex< Color > colorMap, BiIndex< String > imageMap)
Grid (Dimension size, BiIndex< Color > colorMap, BiIndex< String > imageMap, Turtle turtle)
void setBGColor (Color newBGColor)
void addTurtle (Turtle newTurtle)
Dimension getSize ()
Color getBGColor ()
List< Turtle > getAllTurtles ()
List< Turtle > getActiveTurtles ()
List< Turtle > getShowingTurtles ()
Turtle getTurtleById (int id)
double setActiveTurtles (List< Turtle > turtles)
void setActiveTurtle (Turtle turtle)
List< Line > getLines ()
List< Stamp > getStamps ()
List< DrawableImage > getDrawableImages ()
void setDimensions (int width, int height)
Private Attributes
Dimension size
Color bgColor
HashMap< Integer, Turtle > allTurtles
ArrayList< Turtle > activeTurtles
BiIndex< Color > colorMap
BiIndex< String > imageMap
Detailed Description
Definition at line 10 of file Grid.java.
Constructor & Destructor Documentation
backend.Grid.Grid (Dimension size, BiIndex< Color > colorMap, BiIndex< String > imageMap)
Definition at line 19 of file Grid.java.
References backend.Grid.colorMap, backend.Defaults.GRID_COLOR_INDEX, backend.Grid.imageMap, and backend.Grid.size.
backend.Grid.Grid (Dimension size, BiIndex< Color > colorMap, BiIndex< String > imageMap, Turtle turtle)
Definition at line 28 of file Grid.java.
References backend.Grid.addTurtle(), backend.Grid.colorMap, backend.Grid.imageMap, and backend.Grid.size.
Member Function Documentation
void backend.Grid.addTurtle (Turtle newTurtle)
Definition at line 37 of file Grid.java.
References backend.Turtle.getID().
Referenced by backend.Grid.Grid().
List<Turtle> backend.Grid.getActiveTurtles ()
Definition at line 56 of file Grid.java.
Referenced by backend.command.TurtleCommand.activeTurtles().
List<Turtle> backend.Grid.getAllTurtles ()
Definition at line 52 of file Grid.java.
Referenced by backend.command.TurtleCommand.allTurtles(), gui.TopMenu.createDisplayMenuItems(), backend.Grid.getShowingTurtles(), gui.SlogoTab.setButtonActions(), and gui.SlogoTab.updatePanels().
Color backend.Grid.getBGColor ()
Definition at line 48 of file Grid.java.
References backend.Grid.bgColor.
List<DrawableImage> backend.Grid.getDrawableImages ()
Definition at line 112 of file Grid.java.
References backend.Grid.getShowingTurtles(), and backend.Grid.getStamps().
Referenced by backend.Model.printDrawableImages().
List<Line> backend.Grid.getLines ()
Definition at line 91 of file Grid.java.
Referenced by backend.Model.printLines(), gui.SlogoTab.setButtonActions(), and gui.SlogoTab.updatePanels().
List<Turtle> backend.Grid.getShowingTurtles ()
Definition at line 60 of file Grid.java.
References backend.Grid.getAllTurtles().
Referenced by backend.Grid.getDrawableImages().
Dimension backend.Grid.getSize ()
Definition at line 44 of file Grid.java.
References backend.Grid.size.
List<Stamp> backend.Grid.getStamps ()
Definition at line 102 of file Grid.java.
Referenced by backend.Grid.getDrawableImages().
Turtle backend.Grid.getTurtleById (int id)
Definition at line 70 of file Grid.java.
void backend.Grid.setActiveTurtle (Turtle turtle)
Definition at line 86 of file Grid.java.
Referenced by backend.command.ActiveTurtleCommand.execute().
double backend.Grid.setActiveTurtles (List< Turtle > turtles)
Definition at line 80 of file Grid.java.
Referenced by backend.command.Tell.execute(), and backend.command.Ask.execute().
void backend.Grid.setBGColor (Color newBGColor)
Definition at line 33 of file Grid.java.
Referenced by backend.command.SetBackground.execute().
void backend.Grid.setDimensions (int width, int height)
Definition at line 119 of file Grid.java.
Referenced by gui.SlogoTab.SlogoTab().
Member Data Documentation
ArrayList<Turtle> backend.Grid.activeTurtles private
Definition at line 15 of file Grid.java.
HashMap<Integer, Turtle> backend.Grid.allTurtles private
Definition at line 14 of file Grid.java.
Color backend.Grid.bgColor private
Definition at line 13 of file Grid.java.
Referenced by backend.Grid.getBGColor().
BiIndex<Color> backend.Grid.colorMap private
Definition at line 16 of file Grid.java.
Referenced by backend.Grid.Grid().
BiIndex<String> backend.Grid.imageMap private
Definition at line 17 of file Grid.java.
Referenced by backend.Grid.Grid().
Dimension backend.Grid.size private
Definition at line 12 of file Grid.java.
Referenced by backend.Grid.getSize(), and backend.Grid.Grid().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/Grid.java