slogo_team14: gui.TabPanel Class Reference
gui.TabPanel Class Reference
Public Member Functions
TabPanel (Double tabPanelHeightPct, Double screenHeight, Double screenWidth, Main main, Model model)
void makeNewTab ()
Package Attributes
double screenHeight
double screenWidth
double tabPaneHeightPct
double topOffsetPct = .025
Main main
Model myModel
Private Member Functions
void makeTabPane (Double tabPaneHeightPct)
Private Attributes
HashMap< Tab, SlogoTab > tabSlogoTabMap = new HashMap<>()
Detailed Description
Definition at line 11 of file TabPanel.java.
Constructor & Destructor Documentation
gui.TabPanel.TabPanel (Double tabPanelHeightPct, Double screenHeight, Double screenWidth, Main main, Model model)
Definition at line 22 of file TabPanel.java.
References gui.TabPanel.main, gui.TabPanel.makeTabPane(), gui.TabPanel.screenHeight, and gui.TabPanel.screenWidth.
Member Function Documentation
void gui.TabPanel.makeNewTab ()
Definition at line 51 of file TabPanel.java.
References gui.Main.setActiveTab().
Referenced by gui.TopMenu.createFileMenuItems(), and gui.Main.start().
void gui.TabPanel.makeTabPane (Double tabPaneHeightPct) private
Definition at line 34 of file TabPanel.java.
References gui.Main.setActiveTab().
Referenced by gui.TabPanel.TabPanel().
Member Data Documentation
Main gui.TabPanel.main package
Definition at line 17 of file TabPanel.java.
Referenced by gui.TabPanel.TabPanel().
Model gui.TabPanel.myModel package
Definition at line 19 of file TabPanel.java.
double gui.TabPanel.screenHeight package
Definition at line 13 of file TabPanel.java.
Referenced by gui.TabPanel.TabPanel().
double gui.TabPanel.screenWidth package
Definition at line 14 of file TabPanel.java.
Referenced by gui.TabPanel.TabPanel().
double gui.TabPanel.tabPaneHeightPct package
Definition at line 15 of file TabPanel.java.
HashMap<Tab, SlogoTab> gui.TabPanel.tabSlogoTabMap = new HashMap<>() private
Definition at line 18 of file TabPanel.java.
double gui.TabPanel.topOffsetPct = .025 package
Definition at line 16 of file TabPanel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/gui/TabPanel.java