slogo_team14: backend.command.CommandList Class Reference
backend.command.CommandList Class Reference
Public Member Functions
CommandList (StringPair stringPair, Command parent)
boolean needsParams ()
void setComplete ()
Double execute ()
List< Double > executeList ()
int size ()
Public Member Functions inherited from backend.command.Command
Command (StringPair stringPair, int numParams, Command parent)
abstract Double execute ()
String toString ()
String getTypedString ()
String getProperty ()
boolean needsParams ()
void setParam (Command newParam)
Command getParam (int index)
boolean hasParent ()
Double executeParam (int paramIndex)
Double getReturnVal ()
Double getParamReturnVal (int paramIndex)
ArrayList< Command > getParams ()
Command getParent ()
int getIndentLevel ()
Protected Member Functions
String preParamsFormatString ()
String postParamsFormatString ()
String interParamFormatString ()
Protected Member Functions inherited from backend.command.Command
String preParamsFormatString ()
String indentString ()
String postParamsFormatString ()
String interParamFormatString ()
boolean parentIsList ()
Private Attributes
boolean listComplete
Additional Inherited Members
Protected Attributes inherited from backend.command.Command
int numParams
ArrayList< Command > params
Command parent
Package Functions inherited from backend.command.Command
public< T extends Command > T getParam (int index, Class< T > type)
Package Attributes inherited from backend.command.Command
int indentLevel
Double returnVal
Detailed Description
Definition at line 6 of file CommandList.java.
Constructor & Destructor Documentation
backend.command.CommandList.CommandList (StringPair stringPair, Command parent)
Definition at line 10 of file CommandList.java.
Member Function Documentation
Double backend.command.CommandList.execute ()
Definition at line 39 of file CommandList.java.
References backend.command.CommandList.executeList().
Referenced by backend.command.UserInstructionRetriever.execute().
List<Double> backend.command.CommandList.executeList ()
Definition at line 44 of file CommandList.java.
References backend.command.Command.params.
Referenced by backend.command.CommandList.execute().
String backend.command.CommandList.interParamFormatString () protected
Definition at line 26 of file CommandList.java.
boolean backend.command.CommandList.needsParams ()
Definition at line 31 of file CommandList.java.
References backend.command.CommandList.listComplete.
String backend.command.CommandList.postParamsFormatString () protected
Definition at line 21 of file CommandList.java.
References backend.command.Command.indentString(), and backend.command.Command.parent.
String backend.command.CommandList.preParamsFormatString () protected
Definition at line 16 of file CommandList.java.
References backend.command.Command.getTypedString(), backend.command.Command.indentString(), and backend.command.Command.parent.
void backend.command.CommandList.setComplete ()
Definition at line 35 of file CommandList.java.
int backend.command.CommandList.size ()
Definition at line 52 of file CommandList.java.
References backend.command.Command.params.
Referenced by backend.command.UserInstructionRetriever.genVariables(), and backend.command.UserInstructionRetriever.getNumParams().
Member Data Documentation
boolean backend.command.CommandList.listComplete private
Definition at line 8 of file CommandList.java.
Referenced by backend.command.CommandList.needsParams().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/command/CommandList.java