slogo_team14: gui.DrawingArea Class Reference
gui.DrawingArea Class Reference
Public Member Functions
DrawingArea (double drawingAreaWidth, double drawingAreaHeight, double drawingAreaXLocation, double drawingAreaYLocation)
javafx.scene.paint.Color awtToPaint (java.awt.Color c)
Protected Member Functions
void drawLines (List< backend.Line > lines)
void drawTurtles (List< Turtle > turtles)
Point convertCoordinates (Point point)
Protected Attributes
double drawingAreaWidth
double drawingAreaHeight
double drawingAreaXLocation
double drawingAreaYLocation
Canvas drawingCanvas
HashMap< Turtle, TurtleImage > turtleMap = new HashMap<>()
Private Member Functions
Point positionPointRelativeToLines (Point turtleLocation, TurtleImage turtleImage)
Detailed Description
Definition at line 16 of file DrawingArea.java.
Constructor & Destructor Documentation
gui.DrawingArea.DrawingArea (double drawingAreaWidth, double drawingAreaHeight, double drawingAreaXLocation, double drawingAreaYLocation)
Definition at line 25 of file DrawingArea.java.
References gui.DrawingArea.drawingAreaHeight, gui.DrawingArea.drawingAreaWidth, gui.DrawingArea.drawingAreaXLocation, gui.DrawingArea.drawingAreaYLocation, and gui.DrawingArea.drawingCanvas.
Member Function Documentation
javafx.scene.paint.Color gui.DrawingArea.awtToPaint (java.awt.Color c)
Definition at line 124 of file DrawingArea.java.
Referenced by gui.DrawingArea.drawLines().
Point gui.DrawingArea.convertCoordinates (Point point) protected
Definition at line 109 of file DrawingArea.java.
References gui.DrawingArea.drawingAreaHeight, and gui.DrawingArea.drawingAreaWidth.
Referenced by gui.DrawingArea.drawLines(), and gui.DrawingArea.drawTurtles().
void gui.DrawingArea.drawLines (List< backend.Line > lines) protected
Definition at line 53 of file DrawingArea.java.
References gui.DrawingArea.awtToPaint(), and gui.DrawingArea.convertCoordinates().
Referenced by gui.SlogoTab.setButtonActions(), and gui.SlogoTab.updatePanels().
void gui.DrawingArea.drawTurtles (List< Turtle > turtles) protected
Definition at line 67 of file DrawingArea.java.
References gui.DrawingArea.convertCoordinates(), gui.TurtleImage.orientTurtle(), gui.DrawingArea.positionPointRelativeToLines(), gui.TurtleImage.setLocation(), gui.TurtleImage.sizeTurtle(), and gui.TurtleImage.updateImage().
Referenced by gui.SlogoTab.setButtonActions(), and gui.SlogoTab.updatePanels().
Point gui.DrawingArea.positionPointRelativeToLines (Point turtleLocation, TurtleImage turtleImage) private
Definition at line 95 of file DrawingArea.java.
References gui.TurtleImage.turtleWidthPct.
Referenced by gui.DrawingArea.drawTurtles().
Member Data Documentation
double gui.DrawingArea.drawingAreaHeight protected
Definition at line 19 of file DrawingArea.java.
Referenced by gui.DrawingArea.convertCoordinates(), and gui.DrawingArea.DrawingArea().
double gui.DrawingArea.drawingAreaWidth protected
Definition at line 18 of file DrawingArea.java.
Referenced by gui.DrawingArea.convertCoordinates(), and gui.DrawingArea.DrawingArea().
double gui.DrawingArea.drawingAreaXLocation protected
Definition at line 20 of file DrawingArea.java.
Referenced by gui.DrawingArea.DrawingArea().
double gui.DrawingArea.drawingAreaYLocation protected
Definition at line 21 of file DrawingArea.java.
Referenced by gui.DrawingArea.DrawingArea().
Canvas gui.DrawingArea.drawingCanvas protected
Definition at line 22 of file DrawingArea.java.
Referenced by gui.DrawingArea.DrawingArea().
HashMap<Turtle, TurtleImage> gui.DrawingArea.turtleMap = new HashMap<>() protected
Definition at line 23 of file DrawingArea.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/gui/DrawingArea.java