slogo_team14: backend.Model Class Reference
backend.Model Class Reference
Public Member Functions
Model ()
BiMap< Integer, Color > getColorMap ()
BiMap< Integer, String > getImageMap ()
void parseProgram (String prog)
Command executeCommand (Command command)
Command executeNextCommand ()
List< Command > executeAllCommands ()
void setUserVariable (String name, Variable newVar)
void setUserVariable (String name, double val)
void setUserVariable (Variable var, double val)
void setLanguage (String language)
Grid getGrid ()
List< Command > getExecutedCommands ()
List< Command > getPendingCommands ()
Map< String, Variable > getUserVariables ()
Map< String, UserInstructionContainer > getUserFunctions ()
String getHelpPagePath ()
void printCommandTree ()
void printCommands (ArrayList< Command > params)
Private Member Functions
void printLines ()
void printDrawableImages ()
Private Attributes
BiIndex< Color > colorMap
BiIndex< String > imageMap
Grid grid
Queue< Command > pendingCommands
HashMap< String, Variable > userVariables
HashMap< String, UserInstructionContainer > userInstructions
String helpPagePath
CommandFactory comFactory
SLogoParser parser
Static Private Attributes
static Stack< Command > executedCommands
Detailed Description
Definition at line 15 of file Model.java.
Constructor & Destructor Documentation
backend.Model.Model ()
Definition at line 28 of file Model.java.
References backend.Defaults.COLOR_MAP, backend.Defaults.GRID_HEIGHT, backend.Defaults.GRID_WIDTH, backend.Defaults.HELP_PAGE_PATH, and backend.Defaults.IMAGE_MAP.
Member Function Documentation
List<Command> backend.Model.executeAllCommands ()
Definition at line 67 of file Model.java.
References backend.Model.executedCommands, and backend.Model.executeNextCommand().
Referenced by gui.SlogoTab.setButtonActions().
Command backend.Model.executeCommand (Command command)
Definition at line 54 of file Model.java.
References backend.command.Command.execute().
Referenced by gui.SlogoTab.updatePanels().
Command backend.Model.executeNextCommand ()
Definition at line 60 of file Model.java.
References backend.command.Command.execute().
Referenced by backend.Model.executeAllCommands(), and gui.SlogoTab.setButtonActions().
BiMap<Integer, Color> backend.Model.getColorMap ()
Definition at line 42 of file Model.java.
References backend.Model.colorMap.
Referenced by backend.command.ModelCommand.colorMap().
List<Command> backend.Model.getExecutedCommands ()
Definition at line 97 of file Model.java.
References backend.Model.executedCommands.
Referenced by gui.SlogoTab.updatePanels().
Grid backend.Model.getGrid ()
Definition at line 93 of file Model.java.
References backend.Model.grid.
Referenced by gui.TopMenu.createDisplayMenuItems(), backend.command.ModelCommand.grid(), backend.Model.printLines(), gui.SlogoTab.setButtonActions(), gui.SlogoTab.SlogoTab(), and gui.SlogoTab.updatePanels().
String backend.Model.getHelpPagePath ()
Definition at line 113 of file Model.java.
References backend.Model.helpPagePath.
BiMap<Integer, String> backend.Model.getImageMap ()
Definition at line 46 of file Model.java.
References backend.Model.imageMap.
Referenced by backend.command.ModelCommand.imageMap().
List<Command> backend.Model.getPendingCommands ()
Definition at line 101 of file Model.java.
References backend.Model.pendingCommands.
Map<String, UserInstructionContainer> backend.Model.getUserFunctions ()
Definition at line 109 of file Model.java.
References backend.Model.userInstructions.
Referenced by backend.command.ModelCommand.userInstructions().
Map<String, Variable> backend.Model.getUserVariables ()
Definition at line 105 of file Model.java.
References backend.Model.userVariables.
Referenced by gui.SlogoTab.setVariablesBox(), and backend.command.ModelCommand.userVariables().
void backend.Model.parseProgram (String prog)
Definition at line 50 of file Model.java.
References backend.SLogoParser.parseProgram().
Referenced by gui.SlogoTab.setButtonActions().
void backend.Model.printCommands (ArrayList< Command > params)
Definition at line 134 of file Model.java.
Referenced by backend.Model.printCommandTree().
void backend.Model.printCommandTree ()
Definition at line 126 of file Model.java.
References backend.command.Command.getParams(), and backend.Model.printCommands().
void backend.Model.printDrawableImages () private
Definition at line 143 of file Model.java.
References backend.Grid.getDrawableImages().
void backend.Model.printLines () private
Definition at line 118 of file Model.java.
References backend.Model.getGrid(), and backend.Grid.getLines().
void backend.Model.setLanguage (String language)
Definition at line 89 of file Model.java.
References backend.SLogoParser.changeLanguage().
Referenced by gui.TopMenu.createLanguageMenuItems().
void backend.Model.setUserVariable (String name, Variable newVar)
Definition at line 74 of file Model.java.
Referenced by backend.Model.setUserVariable(), and gui.SlogoTab.setVariablesBox().
void backend.Model.setUserVariable (String name, double val)
Definition at line 78 of file Model.java.
References backend.Model.setUserVariable().
void backend.Model.setUserVariable (Variable var, double val)
Definition at line 83 of file Model.java.
References backend.Variable.getName(), and backend.Model.setUserVariable().
Member Data Documentation
BiIndex<Color> backend.Model.colorMap private
Definition at line 17 of file Model.java.
Referenced by backend.Model.getColorMap().
CommandFactory backend.Model.comFactory private
Definition at line 25 of file Model.java.
Stack<Command> backend.Model.executedCommands static private
Definition at line 21 of file Model.java.
Referenced by backend.Model.executeAllCommands(), and backend.Model.getExecutedCommands().
Grid backend.Model.grid private
Definition at line 19 of file Model.java.
Referenced by backend.Model.getGrid().
String backend.Model.helpPagePath private
Definition at line 24 of file Model.java.
Referenced by backend.Model.getHelpPagePath().
BiIndex<String> backend.Model.imageMap private
Definition at line 18 of file Model.java.
Referenced by backend.Model.getImageMap().
SLogoParser backend.Model.parser private
Definition at line 26 of file Model.java.
Queue<Command> backend.Model.pendingCommands private
Definition at line 20 of file Model.java.
Referenced by backend.Model.getPendingCommands().
HashMap<String, UserInstructionContainer> backend.Model.userInstructions private
Definition at line 23 of file Model.java.
Referenced by backend.Model.getUserFunctions().
HashMap<String, Variable> backend.Model.userVariables private
Definition at line 22 of file Model.java.
Referenced by backend.Model.getUserVariables().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/Model.java