slogo_team14: gui.TopMenu Class Reference
gui.TopMenu Class Reference
Public Member Functions
TopMenu (double overlayWidth, double overlayHeight, double heightPct, Model myModel, TabPanel tabPanel)
void addMenuBar ()
void createFileMenuItems (Menu file)
void createDisplayMenuItems (Menu turtle)
void createLanguageMenuItems (Menu language)
void createHelpMenuItems (Menu help)
Color openColorPicker ()
java.awt.Color paintToAwt (javafx.scene.paint.Color c)
Protected Attributes
double overlayWidth
double overlayHeight
double heightPct
Model myModel
TabPanel tabPanel
Detailed Description
Definition at line 21 of file TopMenu.java.
Constructor & Destructor Documentation
gui.TopMenu.TopMenu (double overlayWidth, double overlayHeight, double heightPct, Model myModel, TabPanel tabPanel)
Definition at line 30 of file TopMenu.java.
References gui.TopMenu.addMenuBar(), gui.TopMenu.heightPct, gui.TopMenu.myModel, gui.TopMenu.overlayHeight, gui.TopMenu.overlayWidth, and gui.TopMenu.tabPanel.
Member Function Documentation
void gui.TopMenu.addMenuBar ()
Definition at line 42 of file TopMenu.java.
References gui.TopMenu.createDisplayMenuItems(), gui.TopMenu.createFileMenuItems(), gui.TopMenu.createHelpMenuItems(), and gui.TopMenu.createLanguageMenuItems().
Referenced by gui.TopMenu.TopMenu().
void gui.TopMenu.createDisplayMenuItems (Menu turtle)
Definition at line 105 of file TopMenu.java.
References backend.Grid.getAllTurtles(), backend.Model.getGrid(), and gui.TopMenu.openColorPicker().
Referenced by gui.TopMenu.addMenuBar().
void gui.TopMenu.createFileMenuItems (Menu file)
Definition at line 69 of file TopMenu.java.
References gui.TabPanel.makeNewTab().
Referenced by gui.TopMenu.addMenuBar().
void gui.TopMenu.createHelpMenuItems (Menu help)
Definition at line 194 of file TopMenu.java.
Referenced by gui.TopMenu.addMenuBar().
void gui.TopMenu.createLanguageMenuItems (Menu language)
Definition at line 158 of file TopMenu.java.
References backend.Model.setLanguage().
Referenced by gui.TopMenu.addMenuBar().
Color gui.TopMenu.openColorPicker ()
Definition at line 212 of file TopMenu.java.
References gui.ColorPickingScreen.getColor(), and gui.ColorPickingScreen.start().
Referenced by gui.TopMenu.createDisplayMenuItems().
java.awt.Color gui.TopMenu.paintToAwt (javafx.scene.paint.Color c)
Definition at line 225 of file TopMenu.java.
Member Data Documentation
double gui.TopMenu.heightPct protected
Definition at line 25 of file TopMenu.java.
Referenced by gui.TopMenu.TopMenu().
Model gui.TopMenu.myModel protected
Definition at line 27 of file TopMenu.java.
Referenced by gui.TopMenu.TopMenu().
double gui.TopMenu.overlayHeight protected
Definition at line 24 of file TopMenu.java.
Referenced by gui.TopMenu.TopMenu().
double gui.TopMenu.overlayWidth protected
Definition at line 23 of file TopMenu.java.
Referenced by gui.TopMenu.TopMenu().
TabPanel gui.TopMenu.tabPanel protected
Definition at line 28 of file TopMenu.java.
Referenced by gui.Main.start(), and gui.TopMenu.TopMenu().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/gui/TopMenu.java