slogo_team14: backend.SLogoParser Class Reference
backend.SLogoParser Class Reference
Public Member Functions
SLogoParser (CommandFactory comFactory, String language)
SLogoParser (CommandFactory comFactory)
void genPatternList ()
void changeLanguage (String newLanguage)
Queue< Command > parseProgram (String prog) throws IllegalArgumentException
Private Member Functions
Command bubbleUp (Command targetNode)
boolean match (String input, Pattern regex)
List< Entry< String, Pattern > > makePatterns (String syntax)
ArrayList< StringPair > genPropertyList (String[] tests)
Private Attributes
CommandFactory comFactory
List< Entry< String, Pattern > > patterns
String language
Detailed Description
Definition at line 15 of file SLogoParser.java.
Constructor & Destructor Documentation
backend.SLogoParser.SLogoParser (CommandFactory comFactory, String language)
Definition at line 21 of file SLogoParser.java.
References backend.SLogoParser.comFactory, backend.SLogoParser.genPatternList(), and backend.SLogoParser.language.
backend.SLogoParser.SLogoParser (CommandFactory comFactory)
Definition at line 27 of file SLogoParser.java.
References backend.SLogoParser.comFactory, and backend.Defaults.LANGUAGE.
Member Function Documentation
Command backend.SLogoParser.bubbleUp (Command targetNode) private
Definition at line 83 of file SLogoParser.java.
References backend.command.Command.getParent(), backend.command.Command.hasParent(), and backend.command.Command.needsParams().
Referenced by backend.SLogoParser.parseProgram().
void backend.SLogoParser.changeLanguage (String newLanguage)
Definition at line 37 of file SLogoParser.java.
References backend.SLogoParser.genPatternList().
Referenced by backend.Model.setLanguage().
void backend.SLogoParser.genPatternList ()
Definition at line 31 of file SLogoParser.java.
References backend.SLogoParser.makePatterns().
Referenced by backend.SLogoParser.changeLanguage(), and backend.SLogoParser.SLogoParser().
ArrayList<StringPair> backend.SLogoParser.genPropertyList (String[] tests) private
Definition at line 115 of file SLogoParser.java.
References backend.SLogoParser.match().
Referenced by backend.SLogoParser.parseProgram().
List<Entry<String, Pattern> > backend.SLogoParser.makePatterns (String syntax) private
Definition at line 101 of file SLogoParser.java.
Referenced by backend.SLogoParser.genPatternList().
boolean backend.SLogoParser.match (String input, Pattern regex) private
Definition at line 94 of file SLogoParser.java.
Referenced by backend.SLogoParser.genPropertyList().
Queue<Command> backend.SLogoParser.parseProgram (String prog) throws IllegalArgumentException
Definition at line 42 of file SLogoParser.java.
References backend.SLogoParser.bubbleUp(), backend.SLogoParser.genPropertyList(), backend.command.CommandFactory.getCommand(), backend.command.Command.needsParams(), and backend.command.Command.setParam().
Referenced by backend.Model.parseProgram().
Member Data Documentation
CommandFactory backend.SLogoParser.comFactory private
Definition at line 17 of file SLogoParser.java.
Referenced by backend.SLogoParser.SLogoParser().
String backend.SLogoParser.language private
Definition at line 19 of file SLogoParser.java.
Referenced by backend.SLogoParser.SLogoParser().
List<Entry<String, Pattern> > backend.SLogoParser.patterns private
Definition at line 18 of file SLogoParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/SLogoParser.java