slogo_team14: gui.ColorPickingScreen Class Reference
gui.ColorPickingScreen Class Reference
Public Member Functions
void start (Stage stage)
Color getColor ()
Static Public Member Functions
static void main (String[] args)
static void setColor (Color color)
Static Private Attributes
static Color color
Detailed Description
Definition at line 13 of file ColorPickingScreen.java.
Member Function Documentation
Color gui.ColorPickingScreen.getColor ()
Definition at line 52 of file ColorPickingScreen.java.
References gui.ColorPickingScreen.color.
Referenced by gui.TopMenu.openColorPicker().
static void gui.ColorPickingScreen.main (String[] args) static
Definition at line 16 of file ColorPickingScreen.java.
static void gui.ColorPickingScreen.setColor (Color color) static
Definition at line 56 of file ColorPickingScreen.java.
References gui.ColorPickingScreen.color.
Referenced by gui.ColorPickingScreen.start().
void gui.ColorPickingScreen.start (Stage stage)
Definition at line 21 of file ColorPickingScreen.java.
References gui.ColorPickingScreen.setColor().
Referenced by gui.TopMenu.openColorPicker().
Member Data Documentation
Color gui.ColorPickingScreen.color static private
Definition at line 15 of file ColorPickingScreen.java.
Referenced by gui.ColorPickingScreen.getColor(), and gui.ColorPickingScreen.setColor().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/gui/ColorPickingScreen.java