slogo_team14: gui.SlogoTab Class Reference
gui.SlogoTab Class Reference
Public Member Functions
SlogoTab (Model model)
Private Member Functions
void updatePanels ()
void setVariablesBox ()
void setButtonActions ()
void setStageToFillWindow (Double screenWidth, Double screenHeight)
double getScreenHeight (Rectangle2D bounds)
double getScreenWidth (Rectangle2D bounds)
Private Attributes
double infoBoxWidthPct = .2
double infoBoxHeightPct = .4725
double commandBoxWidthPct = .5
double commandBoxHeightPct = .25
double topMenuHeightPct = .055
double buttonWidthPct = .1
double buttonHeightPct = .25
RunButtons runButtons
CommandBox commandBox
DrawingArea turtlePanel
PreviousCommandsBox prevCommandsBox
StatusBox statusBox
UserVariablesBox userVariablesBox
Model myModel
Detailed Description
Definition at line 28 of file SlogoTab.java.
Constructor & Destructor Documentation
gui.SlogoTab.SlogoTab (Model model)
Definition at line 50 of file SlogoTab.java.
References backend.Model.getGrid(), gui.SlogoTab.getScreenHeight(), gui.SlogoTab.getScreenWidth(), gui.textAreas.AbstractEditableTextBox.getxLocation(), gui.textAreas.AbstractEditableTextBox.getyLocation(), gui.SlogoTab.infoBoxWidthPct, gui.SlogoTab.setButtonActions(), backend.Grid.setDimensions(), and gui.SlogoTab.topMenuHeightPct.
Member Function Documentation
double gui.SlogoTab.getScreenHeight (Rectangle2D bounds) private
Definition at line 261 of file SlogoTab.java.
Referenced by gui.SlogoTab.SlogoTab().
double gui.SlogoTab.getScreenWidth (Rectangle2D bounds) private
Definition at line 268 of file SlogoTab.java.
Referenced by gui.SlogoTab.SlogoTab().
void gui.SlogoTab.setButtonActions () private
Definition at line 216 of file SlogoTab.java.
References gui.DrawingArea.drawLines(), gui.DrawingArea.drawTurtles(), backend.Model.executeAllCommands(), backend.Model.executeNextCommand(), backend.Grid.getAllTurtles(), backend.Model.getGrid(), backend.Grid.getLines(), gui.RunButtons.getRunButton(), gui.RunButtons.getStepButton(), gui.textAreas.CommandBox.getText(), backend.Model.parseProgram(), and gui.SlogoTab.updatePanels().
Referenced by gui.SlogoTab.SlogoTab().
void gui.SlogoTab.setStageToFillWindow (Double screenWidth, Double screenHeight) private
Definition at line 251 of file SlogoTab.java.
void gui.SlogoTab.setVariablesBox () private
Definition at line 189 of file SlogoTab.java.
References gui.textAreas.UserVariablesBox.getFields(), gui.textAreas.UserVariablesBox.getLabels(), backend.Model.getUserVariables(), and backend.Model.setUserVariable().
Referenced by gui.SlogoTab.updatePanels().
void gui.SlogoTab.updatePanels () private
Definition at line 148 of file SlogoTab.java.
References gui.DrawingArea.drawLines(), gui.DrawingArea.drawTurtles(), backend.Model.executeCommand(), backend.Grid.getAllTurtles(), backend.Model.getExecutedCommands(), backend.Model.getGrid(), backend.Grid.getLines(), gui.textAreas.PreviousCommandsBox.setBoxes(), gui.textAreas.AbstractEditableTextBox.setText(), and gui.SlogoTab.setVariablesBox().
Referenced by gui.SlogoTab.setButtonActions().
Member Data Documentation
double gui.SlogoTab.buttonHeightPct = .25 private
Definition at line 36 of file SlogoTab.java.
double gui.SlogoTab.buttonWidthPct = .1 private
Definition at line 35 of file SlogoTab.java.
CommandBox gui.SlogoTab.commandBox private
Definition at line 40 of file SlogoTab.java.
double gui.SlogoTab.commandBoxHeightPct = .25 private
Definition at line 33 of file SlogoTab.java.
double gui.SlogoTab.commandBoxWidthPct = .5 private
Definition at line 32 of file SlogoTab.java.
double gui.SlogoTab.infoBoxHeightPct = .4725 private
Definition at line 31 of file SlogoTab.java.
double gui.SlogoTab.infoBoxWidthPct = .2 private
Definition at line 30 of file SlogoTab.java.
Referenced by gui.SlogoTab.SlogoTab().
Model gui.SlogoTab.myModel private
Definition at line 48 of file SlogoTab.java.
PreviousCommandsBox gui.SlogoTab.prevCommandsBox private
Definition at line 42 of file SlogoTab.java.
RunButtons gui.SlogoTab.runButtons private
Definition at line 39 of file SlogoTab.java.
StatusBox gui.SlogoTab.statusBox private
Definition at line 43 of file SlogoTab.java.
double gui.SlogoTab.topMenuHeightPct = .055 private
Definition at line 34 of file SlogoTab.java.
Referenced by gui.SlogoTab.SlogoTab().
DrawingArea gui.SlogoTab.turtlePanel private
Definition at line 41 of file SlogoTab.java.
UserVariablesBox gui.SlogoTab.userVariablesBox private
Definition at line 44 of file SlogoTab.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/gui/SlogoTab.java