slogo_team14: backend.Variable Class Reference
backend.Variable Class Reference
Public Member Functions
Variable (String name, double value)
String toString ()
String getName ()
double getValue ()
Private Attributes
String name
double value
Detailed Description
Definition at line 3 of file Variable.java.
Constructor & Destructor Documentation
backend.Variable.Variable (String name, double value)
Definition at line 8 of file Variable.java.
References backend.Variable.name, and backend.Variable.value.
Member Function Documentation
String backend.Variable.getName ()
Definition at line 17 of file Variable.java.
References backend.Variable.name.
Referenced by backend.Model.setUserVariable(), and backend.Variable.toString().
double backend.Variable.getValue ()
Definition at line 21 of file Variable.java.
References backend.Variable.value.
String backend.Variable.toString ()
Definition at line 13 of file Variable.java.
References backend.Variable.getName().
Member Data Documentation
String backend.Variable.name private
Definition at line 5 of file Variable.java.
Referenced by backend.Variable.getName(), and backend.Variable.Variable().
double backend.Variable.value private
Definition at line 6 of file Variable.java.
Referenced by backend.Variable.getValue(), and backend.Variable.Variable().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/Variable.java