slogo_team14: backend.Turtle Class Reference
backend.Turtle Class Reference
Public Member Functions
Turtle (int id, String imageName, Point location, Heading heading, Color penColor, int penWidth)
Turtle (int id, BiIndex< Color > colorMap, BiIndex< String > imageMap)
double move (Double magnitude)
double moveToPoint (Point target)
double jumpToPoint (Point target)
double setHeading (double newAngle)
double faceTowards (Point target)
double rotateRight (double degrees)
double rotateLeft (double degrees)
void setImageByFullPath (String imagePath)
void setImageByName (String imageName)
void stamp ()
List< Stamp > getStamps ()
double setPenDown ()
double setPenUp ()
double isPenDown ()
double isShowing ()
double show ()
double hide ()
String getImagePath ()
String getImageName ()
Point getLocation ()
Heading getHeading ()
List< Line > getLines ()
boolean clearLines ()
boolean clearStamps ()
int getID ()
Pen getPen ()
Package Attributes
ArrayList< Stamp > stamps
Private Attributes
int id
String imagePath
Point location
Heading heading
Pen pen
boolean isVisible
Detailed Description
Definition at line 8 of file Turtle.java.
Constructor & Destructor Documentation
backend.Turtle.Turtle (int id, String imageName, Point location, Heading heading, Color penColor, int penWidth)
Definition at line 18 of file Turtle.java.
References backend.Turtle.heading, backend.Turtle.id, backend.Turtle.location, and backend.Turtle.setImageByName().
backend.Turtle.Turtle (int id, BiIndex< Color > colorMap, BiIndex< String > imageMap)
Definition at line 28 of file Turtle.java.
References backend.Turtle.id, backend.Defaults.PEN_COLOR_INDEX, backend.Defaults.PEN_WIDTH, backend.Defaults.TURTLE_IMG_INDEX, backend.Defaults.TURTLE_START_HEADING, and backend.Defaults.TURTLE_START_POINT.
Member Function Documentation
boolean backend.Turtle.clearLines ()
Definition at line 144 of file Turtle.java.
References backend.Pen.clearLines().
Referenced by backend.command.ClearScreen.execute().
boolean backend.Turtle.clearStamps ()
Definition at line 148 of file Turtle.java.
double backend.Turtle.faceTowards (Point target)
Definition at line 59 of file Turtle.java.
References backend.Turtle.setHeading().
Referenced by backend.command.SetTowards.execute().
Heading backend.Turtle.getHeading ()
Definition at line 136 of file Turtle.java.
References backend.Turtle.heading.
Referenced by backend.command.Heading.execute(), and gui.TurtleImage.orientTurtle().
int backend.Turtle.getID ()
Definition at line 157 of file Turtle.java.
References backend.Turtle.id.
Referenced by backend.Grid.addTurtle(), and backend.command.ID.execute().
String backend.Turtle.getImageName ()
Definition at line 128 of file Turtle.java.
References backend.Defaults.IMAGE_DIRECTORY.
Referenced by backend.command.GetShape.execute().
String backend.Turtle.getImagePath ()
Implements backend.DrawableImage.
Definition at line 124 of file Turtle.java.
References backend.Turtle.imagePath.
Referenced by gui.TurtleImage.setDefaultImagePath(), and gui.TurtleImage.updateImage().
List<Line> backend.Turtle.getLines ()
Definition at line 140 of file Turtle.java.
References backend.Pen.getLines().
Point backend.Turtle.getLocation ()
Implements backend.DrawableImage.
Definition at line 132 of file Turtle.java.
References backend.Turtle.location.
Referenced by backend.command.XCoordinate.execute(), and backend.command.YCoordinate.execute().
Pen backend.Turtle.getPen ()
Definition at line 161 of file Turtle.java.
References backend.Turtle.pen.
Referenced by backend.command.GetPenColor.execute(), backend.command.SetPenSize.execute(), and backend.command.SetPenColor.execute().
List<Stamp> backend.Turtle.getStamps ()
Definition at line 92 of file Turtle.java.
References backend.Turtle.stamps.
double backend.Turtle.hide ()
Definition at line 119 of file Turtle.java.
double backend.Turtle.isPenDown ()
Definition at line 106 of file Turtle.java.
References backend.Pen.isDown.
Referenced by backend.command.IsPenDown.execute().
double backend.Turtle.isShowing ()
Definition at line 110 of file Turtle.java.
Referenced by backend.command.IsShowing.execute().
double backend.Turtle.jumpToPoint (Point target)
Definition at line 46 of file Turtle.java.
Referenced by backend.command.ClearScreen.execute(), and backend.Turtle.moveToPoint().
double backend.Turtle.move (Double magnitude)
Definition at line 32 of file Turtle.java.
References backend.Heading.getAngleRads(), and backend.Turtle.moveToPoint().
Referenced by backend.command.Backward.execute(), and backend.command.Forward.execute().
double backend.Turtle.moveToPoint (Point target)
Definition at line 41 of file Turtle.java.
References backend.Pen.drawLine(), and backend.Turtle.jumpToPoint().
Referenced by backend.command.SetPosition.execute(), backend.command.Home.execute(), and backend.Turtle.move().
double backend.Turtle.rotateLeft (double degrees)
Definition at line 73 of file Turtle.java.
References backend.Heading.getAngle(), and backend.Turtle.setHeading().
Referenced by backend.command.Left.execute().
double backend.Turtle.rotateRight (double degrees)
Definition at line 67 of file Turtle.java.
References backend.Heading.getAngle(), and backend.Turtle.setHeading().
Referenced by backend.command.Right.execute().
double backend.Turtle.setHeading (double newAngle)
Definition at line 52 of file Turtle.java.
References backend.Heading.getAngle().
Referenced by backend.command.SetHeading.execute(), backend.Turtle.faceTowards(), backend.Turtle.rotateLeft(), and backend.Turtle.rotateRight().
void backend.Turtle.setImageByFullPath (String imagePath)
Definition at line 79 of file Turtle.java.
References backend.Turtle.imagePath.
Referenced by gui.TurtleImage.setDefaultImagePath(), and backend.Turtle.setImageByName().
void backend.Turtle.setImageByName (String imageName)
Definition at line 83 of file Turtle.java.
References backend.Defaults.IMAGE_DIRECTORY, and backend.Turtle.setImageByFullPath().
Referenced by backend.command.SetShape.execute(), and backend.Turtle.Turtle().
double backend.Turtle.setPenDown ()
Definition at line 96 of file Turtle.java.
References backend.Pen.setDown().
Referenced by backend.command.PenDown.execute().
double backend.Turtle.setPenUp ()
Definition at line 101 of file Turtle.java.
References backend.Pen.setDown().
Referenced by backend.command.PenUp.execute().
double backend.Turtle.show ()
Definition at line 114 of file Turtle.java.
void backend.Turtle.stamp ()
Definition at line 87 of file Turtle.java.
Referenced by backend.command.Stamp.execute().
Member Data Documentation
Heading backend.Turtle.heading private
Definition at line 13 of file Turtle.java.
Referenced by backend.Turtle.getHeading(), and backend.Turtle.Turtle().
int backend.Turtle.id private
Definition at line 10 of file Turtle.java.
Referenced by backend.Turtle.getID(), and backend.Turtle.Turtle().
String backend.Turtle.imagePath private
Definition at line 11 of file Turtle.java.
Referenced by backend.Turtle.getImagePath(), and backend.Turtle.setImageByFullPath().
boolean backend.Turtle.isVisible private
Definition at line 16 of file Turtle.java.
Point backend.Turtle.location private
Definition at line 12 of file Turtle.java.
Referenced by backend.Turtle.getLocation(), and backend.Turtle.Turtle().
Pen backend.Turtle.pen private
Definition at line 14 of file Turtle.java.
Referenced by backend.Turtle.getPen().
ArrayList<Stamp> backend.Turtle.stamps package
Definition at line 15 of file Turtle.java.
Referenced by backend.Turtle.getStamps().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team14/repository/src/backend/Turtle.java